(()=>{'use strict';const root=document.querySelector('.hero-carousel');if(!root)return;const slides=[...root.querySelectorAll('.carousel-slide')],dots=[...root.querySelectorAll('[data-carousel-dot]')],controls=root.querySelector('.carousel-controls'),pause=root.querySelector('[data-carousel-pause]'),previous=root.querySelector('[data-carousel-prev]'),next=root.querySelector('[data-carousel-next]'),counter=root.querySelector('.carousel-counter'),announcement=root.querySelector('.carousel-announcement'),motion=matchMedia('(prefers-reduced-motion: reduce)');let index=0,paused=motion.matches,hover=false,focused=false,visible=true,timer,start=null,suppressClick=false;
const words={en:['Previous slide','Next slide','Pause slideshow','Play slideshow','Slide'],de:['Vorherige Folie','Nächste Folie','Diashow pausieren','Diashow starten','Folie'],fr:['Diapositive précédente','Diapositive suivante','Mettre en pause','Lancer le diaporama','Diapositive'],es:['Anterior','Siguiente','Pausar presentación','Reproducir presentación','Diapositiva'],it:['Precedente','Successiva','Pausa presentazione','Avvia presentazione','Diapositiva'],'pt-BR':['Anterior','Próximo','Pausar apresentação','Iniciar apresentação','Slide'],ru:['Предыдущий слайд','Следующий слайд','Приостановить показ','Начать показ','Слайд'],ar:['الشريحة السابقة','الشريحة التالية','إيقاف العرض مؤقتًا','تشغيل العرض','شريحة'],ja:['前のスライド','次のスライド','自動再生を停止','自動再生を開始','スライド'],'zh-CN':['上一张','下一张','暂停轮播','开始轮播','图片']};
function labels(){const w=words[document.documentElement.lang]||words.en;previous.setAttribute('aria-label',w[0]);next.setAttribute('aria-label',w[1]);pause.setAttribute('aria-label',w[paused?3:2]);pause.textContent=paused?'▶':'Ⅱ';dots.forEach((d,i)=>d.setAttribute('aria-label',w[4]+' '+(i+1)));}
function schedule(){clearTimeout(timer);if(!paused&&!hover&&!focused&&visible&&!document.hidden)timer=setTimeout(()=>show(index+1,false),6000);}
function show(n,manual){index=(n+slides.length)%slides.length;slides.forEach((s,i)=>{s.hidden=i!==index});dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(i===index)));counter.textContent=String(index+1).padStart(2,'0')+' / 04';if(manual){paused=true;announcement.textContent=(words[document.documentElement.lang]||words.en)[4]+' '+(index+1)+' / 4';labels();}schedule();}
previous.addEventListener('click',()=>show(index-1,true));next.addEventListener('click',()=>show(index+1,true));dots.forEach((d,i)=>d.addEventListener('click',()=>show(i,true)));pause.addEventListener('click',()=>{paused=!paused;labels();schedule()});root.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hover=true;schedule()}});root.addEventListener('pointerleave',()=>{hover=false;schedule()});root.addEventListener('focusin',()=>{focused=true;schedule()});root.addEventListener('focusout',()=>setTimeout(()=>{focused=root.contains(document.activeElement);schedule()},0));root.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();show(index+(e.key==='ArrowRight'?1:-1),true)}});
const stage=root.querySelector('.carousel-stage');stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')start={x:e.clientX,y:e.clientY}});stage.addEventListener('pointercancel',()=>start=null);stage.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.5){suppressClick=true;show(index+(dx<0?1:-1),true);setTimeout(()=>suppressClick=false,400)}});stage.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopPropagation()}},true);
document.addEventListener('visibilitychange',schedule);document.addEventListener('ketoway:language',labels);motion.addEventListener('change',()=>{if(motion.matches)paused=true;labels();schedule()});if('IntersectionObserver'in window)new IntersectionObserver(es=>{visible=es[0].isIntersecting;schedule()},{threshold:.15}).observe(root);controls.hidden=false;labels();show(0,false);
})();
